# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knapsackproblemrequest',
            name='capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knapsackproblemrequest',
            name='items',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knapsackproblemrequest',
            name='num_items',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
