# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapi', '0003_auto_20170324_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='knapsackproblem',
            name='total_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knapsackproblem',
            name='total_weight',
            field=models.IntegerField(default=0),
        ),
    ]
