# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theapi', '0005_auto_20170324_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knapsackproblemrequest',
            name='finished',
        ),
    ]
